### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by lyx9439** [tinper-bee/bee-layout#2]
1、希望能支持24列的栅格，更灵活，不然有时候会多嵌套一层Col组件。
2、希望能支持非响应式的栅格，不然我想在所有屏幕上都显示相同的布局的话，要写4倍的代码量。
3、Row的margin-left:-15px;margin-right:-15px;会使页面出现横向滚动条，而且目前没发现加了这两条css有什么作用

**Comment by BoyuZhou** [comment]
1、24栅格的问题，我们会进行讨论。
2、非响应式栅格，可以通过设置`xs={xx}`，这样在不同屏幕就是不变的占比。
3、row是作为行显示了，是为了在多栅格嵌套和con和col嵌套时，规避双层padding问题，所以存在的

**Comment by BoyuZhou** [comment]
如果支持24栅格，我们会进行通知，谢谢你的意见。

**Comment by BoyuZhou** [comment]
https://github.com/iuap-design/tinper-bee/issues/33，
关于支持24栅格的讨论，你可以在这里添加你需要的理由

**Comment by lyx9439** [comment]
我觉得row的margin和col的padding都可以去掉啊，如果用户想加padding的话可以自己写啊

**Comment by lyx9439** [comment]
还有con组件是干什么的，我没看到示例代码里用过

**Comment by BoyuZhou** [comment]
栅格布局再设计理念上，是需要增加默认槽宽的（就是padding），一般来说，需要padding的场景比不需要的多，所以我们增加了槽宽。Con是对应响应式布局的容器组件，默认为1080宽度，来做自适应的。
