### ISSUE TITLE
Col组件padding问题

### ISSUE THREAD

**Issue by lyx9439** [tinper-bee/bee-layout#3]
还是建议取消Col组件的padding，因为一旦Col组件下面有个绝对定位元素，设置了width:100%时宽度就会多30px，或者设置max-width:100%时也会多30px，只能用max-width:calc(100% - 30px)这种写法
而且蚂蚁金服的Col组件也没有加padding-left和padding-right

**Comment by lyx9439** [comment]
而且如果多个Col嵌套的话，严重影响布局，全是padding

**Comment by BoyuZhou** [comment]
多Col嵌套，增加Row减少padding

**Comment by lyx9439** [comment]
但是这样会多一个无用的div，我不认为这是好的解决方案

**Comment by BoyuZhou** [comment]
我们实现的是比较受大家认可的bootstrap的栅格系统，目前并没有打算做修改，后续可能会有优化，如果你实在觉得满足不了你的需求，我给你提供这样的解决方案：
```
.clear-padding [class^=col-]{
padding-left: 0;
padding-right: 0;
}
```
